ALTER TABLE "Item" ALTER COLUMN "Item_Type" DROP DEFAULT;
ALTER TABLE "Item" ALTER COLUMN "Item_Type" TYPE TEXT USING "Item_Type"::text;
ALTER TABLE "Item" ALTER COLUMN "Item_Type" SET DEFAULT 'GENERAL';

DROP TYPE IF EXISTS "ItemType";
